name: Deploy Discord Bot v2

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: discord

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run bot
      env:
        DISCORD_BOT_TOKEN: ${{ vars.TOKEN }}  # Utilisez la variable d'environnement définie
      run: |
        python bot.py
